[package]
name = "libcaesium-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
libcaesium = {git = "https://github.com/Lymphatus/libcaesium", default-features = false, features = ["jpg", "png", "webp"] }
libc = "0.2.151"